#!/usr/bin/env bash
# Deploy cra-assistant to the Lightsail host.
#
#   ./deploy/deploy.sh              # rsync, build, migrate, swap, smoke test
#   ./deploy/deploy.sh --no-build   # rsync + migrate only
#   ./deploy/deploy.sh --dry-run    # show what would be sent, change nothing
#
# Config via env (or deploy/deploy.env, which is gitignored):
#   CRA_HOST_IP     Lightsail public IP
#   CRA_SSH_KEY     path to the private key
#   CRA_REMOTE_DIR  default /home/ubuntu/cra
#   CRA_DOMAIN      public hostname, for the smoke test
#   CRA_SSH_OPTS    extra ssh options, e.g. a ControlPath. Lightsail's issued
#                   certificate is good for ~13 minutes and a cold image build
#                   takes longer, so a deploy that authenticates per command
#                   can die halfway. Point this at a live master connection:
#                     -o ControlPath=/tmp/cra-ssh/ctl.sock
#
# Replaces the App Runner script this repo inherited at the fork. App Runner is
# not where anything runs; the Lightsail + compose + Caddy flow is.

set -euo pipefail
cd "$(dirname "$0")/.."

[ -f deploy/deploy.env ] && . deploy/deploy.env

HOST_IP="${CRA_HOST_IP:-}"
SSH_KEY="${CRA_SSH_KEY:-/tmp/cra-ssh/key}"
REMOTE="${CRA_REMOTE_DIR:-/home/ubuntu/cra}"
DOMAIN="${CRA_DOMAIN:-}"
SSH_OPTS="${CRA_SSH_OPTS:-}"
DRY_RUN=""
BUILD=1

for arg in "$@"; do
  case "$arg" in
    --dry-run)  DRY_RUN="--dry-run" ;;
    --no-build) BUILD=0 ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

say()  { printf '\033[1m==> %s\033[0m\n' "$*"; }
fail() { printf '\033[31m%s\033[0m\n' "$*" >&2; exit 1; }

[ -n "$HOST_IP" ] || fail "CRA_HOST_IP is not set. See deploy/deploy.env.example."
SSH="ssh -i ${SSH_KEY} -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new ${SSH_OPTS} ubuntu@${HOST_IP}"

# ---- 0. fail fast on the two things that actually go wrong ------------------

say "Checking SSH"
$SSH 'echo ok' >/dev/null 2>&1 || fail \
"Cannot SSH to ${HOST_IP}.

Lightsail-issued keys are temporary; 'Permission denied (publickey)' usually
means it expired rather than that anything is broken. Re-fetch:

  aws lightsail get-instance-access-details --instance-name <name> \\
    --region eu-north-1 --output json > /tmp/access.json
  mkdir -p /tmp/cra-ssh && chmod 700 /tmp/cra-ssh
  jq -r '.accessDetails.privateKey' /tmp/access.json > /tmp/cra-ssh/key
  jq -r '.accessDetails.certKey'    /tmp/access.json > /tmp/cra-ssh/key-cert.pub
  chmod 600 /tmp/cra-ssh/key /tmp/cra-ssh/key-cert.pub

The cert is not optional. Lightsail issues a certificate alongside the key and
ssh will not authenticate with the key alone — it looks for <key>-cert.pub next
to it. Omitting it fails with exactly the same 'Permission denied (publickey)'
as an expired key, which is why it is easy to chase the wrong problem."

say "Checking the host is provisioned"
$SSH "test -f ${REMOTE}/compose.yml" || fail \
"${REMOTE}/compose.yml is missing on the host.

compose.yml and .env live on the box and are never rsynced — overwriting a
working host config from a laptop is how you lose it. Bootstrap first:
  deploy/bootstrap.sh, which provisions a host from scratch."

$SSH "test -f ${REMOTE}/.env" || fail "${REMOTE}/.env is missing — see deploy/env.example."

# ---- 1. code -----------------------------------------------------------------

# Stamp the build before rsync, so the running server can say what it is.
# Written into the package rather than the repo root because the image
# pip-installs `src/` — at runtime there is no repo to read a file from. It is
# gitignored; a dev tree simply has no `_build` module and reports "dev".
#
# Computed here rather than on the host: `.git` is excluded from the rsync, so
# the host has no way to work out which commit it is running.
say "Stamping the build"
BUILD_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
BUILD_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
  BUILD_COMMIT="${BUILD_COMMIT}-dirty"
  printf '\033[33m Working tree is dirty — deploying uncommitted changes as %s.\033[0m\n' "$BUILD_COMMIT"
fi
cat > src/cra/_build.py <<EOF
# Generated by deploy/deploy.sh. Not committed — see .gitignore.
COMMIT = "${BUILD_COMMIT}"
BRANCH = "${BUILD_BRANCH}"
BUILT_AT = "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
EOF
echo " ${BUILD_BRANCH} @ ${BUILD_COMMIT}"

say "Syncing source${DRY_RUN:+ (dry run)}"
rsync -az --delete $DRY_RUN \
  --exclude=.git --exclude=.venv --exclude=state --exclude=out \
  --exclude=__pycache__ --exclude='*.egg-info' --exclude=.pytest_cache \
  --exclude='*.pyc' \
  --exclude=.env --exclude='.env.*' \
  --exclude=compose.yml --exclude=deploy/deploy.env \
  --rsh="ssh -i ${SSH_KEY} -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new ${SSH_OPTS}" \
  ./ "ubuntu@${HOST_IP}:${REMOTE}/"

# The public site. Served straight off disk by Caddy, never through the
# application — see deploy/Caddyfile.snippet. Kept out of the app directory so
# a static file can never be reached by a path that also routes to the API.
say "Publishing the public site${DRY_RUN:+ (dry run)}"
$SSH "sudo mkdir -p /var/cra-www && sudo chown ubuntu:ubuntu /var/cra-www"
rsync -az --delete $DRY_RUN \
  --rsh="ssh -i ${SSH_KEY} -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new ${SSH_OPTS}" \
  ./www/ "ubuntu@${HOST_IP}:/var/cra-www/"

[ -n "$DRY_RUN" ] && { say "Dry run — stopping here."; exit 0; }

# ---- 2. remember what is currently serving -----------------------------------
#
# The image id the running container was made from, so a failed smoke test has
# something to go back to. Before this, `fail()` exited and left the broken
# container running: a bad deploy took the service down and *kept* it down
# until somebody noticed, which on a compliance tool means somebody mid-deadline
# noticing for us.
#
# An image id, not a tag. Tags move when the next build reuses one; the id is
# the thing that actually was serving. Empty on a first deploy, which is
# handled — there is nothing to roll back to and the script says so.

PREV_IMAGE=$($SSH "docker inspect --format '{{.Image}}' cra 2>/dev/null" || true)
PREV_IMAGE=$(printf '%s' "$PREV_IMAGE" | tr -d '\r\n')
if [ -n "$PREV_IMAGE" ]; then
  # **Tagged, not just remembered.** An id alone is not enough: `up --build`
  # moves `cra-cra:latest` to the new image, the old one becomes dangling, and
  # it is collected — so by the time a rollback needs it, `docker tag` fails
  # with "No such image". That is exactly what happened on the first real
  # failure, and the rollback could not have worked however it was written.
  # A tag is a reference, and a referenced image is not reclaimed.
  $SSH "docker tag ${PREV_IMAGE} cra-cra:rollback" || \
    printf '\033[33mCould not tag the current image; rollback will not be available.\033[0m\n'
  say "Current image: ${PREV_IMAGE#sha256:} (tagged cra-cra:rollback)"
else
  printf '\033[33mNo container running — nothing to roll back to if this fails.\033[0m\n'
fi

rollback() {
  printf '\033[31m%s\033[0m\n' "$*" >&2
  if [ -z "$PREV_IMAGE" ]; then
    printf '\033[31mNo previous image to restore. The service is down — investigate now.\033[0m\n' >&2
    exit 1
  fi
  printf '\033[33mRolling back to %s\033[0m\n' "${PREV_IMAGE#sha256:}" >&2
  # Re-point the tag compose builds to, then recreate **without building**.
  # `--no-build` is what makes the retag stick: without it compose rebuilds from
  # source and puts the broken bits straight back.
  $SSH "cd ${REMOTE} && docker tag cra-cra:rollback cra-cra:latest && \
        docker compose up -d --force-recreate --no-build cra" >&2 || true

  # **Verify the image, not just the health.** The previous version checked
  # /health after the recreate and called a 200 a successful rollback. When the
  # retag failed — which it did, silently, because the old image had been
  # collected — the still-running new container answered 200 a second later and
  # the script reported "Rolled back. The deploy did NOT ship" about a deploy
  # that had shipped. A rollback that cannot fail loudly is worse than none:
  # this one only runs when something is already wrong, and it is believed.
  now=$($SSH "docker inspect --format '{{.Image}}' cra 2>/dev/null" | tr -d '\r\n')
  code=$(_health || echo "dead")
  if [ "$now" = "$PREV_IMAGE" ] && [ "$code" = "200" ]; then
    printf '\033[33mRolled back to %s and healthy. The deploy did NOT ship.\033[0m\n' \
      "${PREV_IMAGE#sha256:}" >&2
  elif [ "$now" = "$PREV_IMAGE" ]; then
    printf '\033[31mRolled back, but it is not answering (%s). The service is down.\033[0m\n' "$code" >&2
  else
    printf '\033[31mROLLBACK FAILED. Running %s, wanted %s. The failed build may still be serving — investigate now.\033[0m\n' \
      "${now#sha256:}" "${PREV_IMAGE#sha256:}" >&2
  fi
  exit 1
}

_health() {
  # Retried, because a recreated container needs a moment: measured at ~2s on
  # this host, and the single immediate probe this used to do reported a
  # healthy deploy as a failure and triggered a rollback nobody needed.
  for _ in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
    c=$($SSH "docker exec cra python -c \"import httpx; print(httpx.get('http://127.0.0.1:8000/health', timeout=3).status_code)\"" 2>/dev/null | tr -d '\r\n')
    [ "$c" = "200" ] && { echo 200; return 0; }
    sleep 2
  done
  echo "${c:-dead}"
  return 1
}

# ---- 3. build ----------------------------------------------------------------
#
# Build only. Starting is a separate step because the migration has to happen
# between the two.

if [ "$BUILD" = "1" ]; then
  say "Building the new image"
  $SSH "cd ${REMOTE} && docker compose build cra" || \
    fail "Build failed. Nothing was swapped — the previous version is still serving."
fi

# ---- 4. migrate, from the new image, before the swap -------------------------
#
# A **one-off container from the image just built**, not `docker exec` into the
# running one. That was the arrangement here and it could not work: alembic the
# *tool* is in the image, but `db_migrations/` is COPYed in at build time, so
# the running container carries the migration set it was built with. Asking it
# for `upgrade head` gets the previous release's head — which is to say,
# nothing new — and the deploy then swapped new code onto the old schema.
#
# It survived because `alembic check` printed a yellow line and let the deploy
# continue, and because every migration until 0015 was additive enough that new
# code met an old schema without visibly breaking. 0015 changed two column
# defaults and backfilled a column, and the deploy reported success having
# applied none of it.
#
# `run --rm --no-deps` gets the new files with the old container still serving,
# which is the property "migrate before swap" was always supposed to buy.
say "Running migrations (from the new image, before the swap)"
$SSH "cd ${REMOTE} && docker compose run --rm --no-deps cra alembic upgrade head" || \
  fail "Migration failed. Nothing was swapped — the previous version is still serving."

# ---- 5. swap -----------------------------------------------------------------

say "Starting the new container"
# `up -d`, never `restart`: compose reads env_file at container creation, so a
# restart silently keeps the environment the old container was created with.
# `--force-recreate` because an unchanged image plus a changed `.env` is exactly
# the case `up -d` alone would skip.
$SSH "cd ${REMOTE} && docker compose up -d --force-recreate --no-build cra" || \
  rollback "Container start failed."

# Rolls back rather than warning. This is the check that caught the bug above
# and could not act on it: a yellow line in several hundred lines of build
# output is a thing nobody reads, and what it detects — new code meeting a
# schema that is not the one it was written against — is the failure the
# ordering exists to prevent.
say "Checking for schema drift"
$SSH "docker exec cra alembic check" || \
  rollback "Schema drift: models and migrations disagree, or a migration did not apply."

# ---- 5. smoke ----------------------------------------------------------------
#
# Every failure below rolls back. The container answering /health is the
# minimum; an unauthenticated MCP POST returning anything but 401 means the
# auth middleware is not in the request path, which is worse than being down.

say "Smoke test"
[ "$(_health)" = "200" ] || rollback "The new container does not answer /health after 30s."
echo " container /health: ok"

if [ -n "$DOMAIN" ]; then
  code=$(curl -s -o /dev/null -w '%{http_code}' "https://${DOMAIN}/health" || true)
  [ "$code" = "200" ] && echo " public  /health: 200" || \
    printf '\033[33m public /health returned %s — check the Caddy @api matcher (deploy/Caddyfile.snippet).\033[0m\n' "$code"

  # An unauthenticated MCP POST must be rejected. Worth asserting on every
  # deploy: a 200 here means the auth middleware is not in the path.
  code=$(curl -s -o /dev/null -w '%{http_code}' -X POST "https://${DOMAIN}/mcp/me/mcp" \
    -H 'Accept: application/json, text/event-stream' -H 'Content-Type: application/json' \
    -d '{"jsonrpc":"2.0","id":1,"method":"initialize"}' || true)
  [ "$code" = "401" ] && echo " unauthenticated MCP: 401 (correct)" || \
    rollback "Unauthenticated MCP returned ${code}, expected 401. The mount is not gated."
fi

say "Deployed."
echo "Alerting: $($SSH "docker exec cra printenv CRA_DEADLINE_ALERTS_ENABLED" 2>/dev/null || echo '(unset — defaults ON)')"
echo "Logs:     ssh -i ${SSH_KEY} ubuntu@${HOST_IP} 'docker logs --tail 100 -f cra'"
