#!/usr/bin/env bash
# Deploy cra-assistant to the Lightsail host.
#
#   ./deploy/deploy.sh              # rsync, rebuild, migrate, smoke test
#   ./deploy/deploy.sh --no-build   # rsync + migrate only
#   ./deploy/deploy.sh --dry-run    # show what would be sent, change nothing
#
# Config via env (or deploy/deploy.env, which is gitignored):
#   CRA_HOST_IP     Lightsail public IP
#   CRA_SSH_KEY     path to the private key
#   CRA_REMOTE_DIR  default /home/ubuntu/cra
#   CRA_DOMAIN      public hostname, for the smoke test
#   CRA_SSH_OPTS    extra ssh options, e.g. a ControlPath. Lightsail's issued
#                   certificate is good for ~13 minutes and a cold image build
#                   takes longer, so a deploy that authenticates per command
#                   can die halfway. Point this at a live master connection:
#                     -o ControlPath=/tmp/cra-ssh/ctl.sock
#
# Replaces the App Runner script this repo inherited at the fork. App Runner is
# not where anything runs; the Lightsail + compose + Caddy flow is.

set -euo pipefail
cd "$(dirname "$0")/.."

[ -f deploy/deploy.env ] && . deploy/deploy.env

HOST_IP="${CRA_HOST_IP:-}"
SSH_KEY="${CRA_SSH_KEY:-/tmp/cra-ssh/key}"
REMOTE="${CRA_REMOTE_DIR:-/home/ubuntu/cra}"
DOMAIN="${CRA_DOMAIN:-}"
SSH_OPTS="${CRA_SSH_OPTS:-}"
DRY_RUN=""
BUILD=1

for arg in "$@"; do
  case "$arg" in
    --dry-run)  DRY_RUN="--dry-run" ;;
    --no-build) BUILD=0 ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

say()  { printf '\033[1m==> %s\033[0m\n' "$*"; }
fail() { printf '\033[31m%s\033[0m\n' "$*" >&2; exit 1; }

[ -n "$HOST_IP" ] || fail "CRA_HOST_IP is not set. See deploy/deploy.env.example."
SSH="ssh -i ${SSH_KEY} -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new ${SSH_OPTS} ubuntu@${HOST_IP}"

# ---- 0. fail fast on the two things that actually go wrong ------------------

say "Checking SSH"
$SSH 'echo ok' >/dev/null 2>&1 || fail \
"Cannot SSH to ${HOST_IP}.

Lightsail-issued keys are temporary; 'Permission denied (publickey)' usually
means it expired rather than that anything is broken. Re-fetch:

  aws lightsail get-instance-access-details --instance-name <name> \\
    --region eu-north-1 --output json > /tmp/access.json
  mkdir -p /tmp/cra-ssh && chmod 700 /tmp/cra-ssh
  jq -r '.accessDetails.privateKey' /tmp/access.json > /tmp/cra-ssh/key
  jq -r '.accessDetails.certKey'    /tmp/access.json > /tmp/cra-ssh/key-cert.pub
  chmod 600 /tmp/cra-ssh/key /tmp/cra-ssh/key-cert.pub

The cert is not optional. Lightsail issues a certificate alongside the key and
ssh will not authenticate with the key alone — it looks for <key>-cert.pub next
to it. Omitting it fails with exactly the same 'Permission denied (publickey)'
as an expired key, which is why it is easy to chase the wrong problem."

say "Checking the host is provisioned"
$SSH "test -f ${REMOTE}/compose.yml" || fail \
"${REMOTE}/compose.yml is missing on the host.

compose.yml and .env live on the box and are never rsynced — overwriting a
working host config from a laptop is how you lose it. Bootstrap first:
  deploy/bootstrap.sh, which provisions a host from scratch."

$SSH "test -f ${REMOTE}/.env" || fail "${REMOTE}/.env is missing — see deploy/env.example."

# ---- 1. code -----------------------------------------------------------------

# Stamp the build before rsync, so the running server can say what it is.
# Written into the package rather than the repo root because the image
# pip-installs `src/` — at runtime there is no repo to read a file from. It is
# gitignored; a dev tree simply has no `_build` module and reports "dev".
#
# Computed here rather than on the host: `.git` is excluded from the rsync, so
# the host has no way to work out which commit it is running.
say "Stamping the build"
BUILD_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
BUILD_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
  BUILD_COMMIT="${BUILD_COMMIT}-dirty"
  printf '\033[33m Working tree is dirty — deploying uncommitted changes as %s.\033[0m\n' "$BUILD_COMMIT"
fi
cat > src/cra/_build.py <<EOF
# Generated by deploy/deploy.sh. Not committed — see .gitignore.
COMMIT = "${BUILD_COMMIT}"
BRANCH = "${BUILD_BRANCH}"
BUILT_AT = "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
EOF
echo " ${BUILD_BRANCH} @ ${BUILD_COMMIT}"

say "Syncing source${DRY_RUN:+ (dry run)}"
rsync -az --delete $DRY_RUN \
  --exclude=.git --exclude=.venv --exclude=state --exclude=out \
  --exclude=__pycache__ --exclude='*.egg-info' --exclude=.pytest_cache \
  --exclude='*.pyc' \
  --exclude=.env --exclude='.env.*' \
  --exclude=compose.yml --exclude=deploy/deploy.env \
  --rsh="ssh -i ${SSH_KEY} -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new ${SSH_OPTS}" \
  ./ "ubuntu@${HOST_IP}:${REMOTE}/"

# The public site. Served straight off disk by Caddy, never through the
# application — see deploy/Caddyfile.snippet. Kept out of the app directory so
# a static file can never be reached by a path that also routes to the API.
say "Publishing the public site${DRY_RUN:+ (dry run)}"
$SSH "sudo mkdir -p /var/cra-www && sudo chown ubuntu:ubuntu /var/cra-www"
rsync -az --delete $DRY_RUN \
  --rsh="ssh -i ${SSH_KEY} -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new ${SSH_OPTS}" \
  ./www/ "ubuntu@${HOST_IP}:/var/cra-www/"

[ -n "$DRY_RUN" ] && { say "Dry run — stopping here."; exit 0; }

# ---- 2. build and start ------------------------------------------------------

if [ "$BUILD" = "1" ]; then
  say "Rebuilding the container"
  # `up -d --build`, never `restart`: compose reads env_file at container
  # creation, so a restart silently keeps the old environment.
  $SSH "cd ${REMOTE} && docker compose up -d --build cra"
else
  $SSH "cd ${REMOTE} && docker compose up -d cra"
fi

# ---- 3. migrate --------------------------------------------------------------

say "Running migrations"
$SSH "docker exec cra alembic upgrade head"

say "Checking for schema drift"
$SSH "docker exec cra alembic check" || \
  printf '\033[33mSchema drift detected — models and migrations disagree.\033[0m\n'

# ---- 4. smoke ----------------------------------------------------------------

say "Smoke test"
$SSH "docker exec cra python -c \"import httpx; r=httpx.get('http://127.0.0.1:8000/health', timeout=5); r.raise_for_status(); print(' container /health:', r.text.strip())\""

if [ -n "$DOMAIN" ]; then
  code=$(curl -s -o /dev/null -w '%{http_code}' "https://${DOMAIN}/health" || true)
  [ "$code" = "200" ] && echo " public  /health: 200" || \
    printf '\033[33m public /health returned %s — check the Caddy @api matcher (deploy/Caddyfile.snippet).\033[0m\n' "$code"

  # An unauthenticated MCP POST must be rejected. Worth asserting on every
  # deploy: a 200 here means the auth middleware is not in the path.
  code=$(curl -s -o /dev/null -w '%{http_code}' -X POST "https://${DOMAIN}/mcp/me/mcp" \
    -H 'Accept: application/json, text/event-stream' -H 'Content-Type: application/json' \
    -d '{"jsonrpc":"2.0","id":1,"method":"initialize"}' || true)
  [ "$code" = "401" ] && echo " unauthenticated MCP: 401 (correct)" || \
    fail "Unauthenticated MCP returned ${code}, expected 401. The mount is not gated — investigate before announcing this deploy."
fi

say "Deployed."
echo "Alerting: $($SSH "docker exec cra printenv CRA_DEADLINE_ALERTS_ENABLED" 2>/dev/null || echo '(unset — defaults ON)')"
echo "Logs:     ssh -i ${SSH_KEY} ubuntu@${HOST_IP} 'docker logs --tail 100 -f cra'"
